import { useEffect, useMemo, useState } from "react";
import { getOperationsSummary, type OperationsSummary } from "./api";

const WINDOWS = [1, 4, 12] as const;
function stamp(value: string) { return new Date(value).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }); }

export function OperationsSummary({ refreshMinutes = 15 }: { refreshMinutes?: number }) {
  const [hours, setHours] = useState<(typeof WINDOWS)[number]>(4);
  const [summaries, setSummaries] = useState<Partial<Record<number, OperationsSummary>>>({});
  const [error, setError] = useState<string>();
  const refreshMs = Math.max(1, Math.min(60, refreshMinutes)) * 60_000;
  useEffect(() => { const controller = new AbortController(); const load = () => getOperationsSummary(hours, controller.signal).then((value) => { setSummaries((current) => ({ ...current, [hours]: value })); setError(undefined); }).catch((cause) => { if (!controller.signal.aborted) setError(cause instanceof Error ? cause.message : "Summary unavailable"); }); load(); const timer = window.setInterval(load, refreshMs); return () => { controller.abort(); window.clearInterval(timer); }; }, [hours, refreshMs]);
  const summary = summaries[hours];
  const grouped = useMemo(() => { if (!summary) return []; const groups = new Map<string, OperationsSummary["threads"]>(); summary.threads.forEach((thread) => groups.set(thread.systemName, [...(groups.get(thread.systemName) ?? []), thread])); return [...groups.entries()]; }, [summary]);
  return <section className="page-card operations-summary"><div className="panel-title"><div><small>OPERATIONS BRIEF</small><h2>AI activity summary</h2><p className="settings-help">Updated every {Math.max(1, Math.min(60, refreshMinutes))} minutes</p></div><div className="summary-tabs" role="tablist">{WINDOWS.map((window) => <button key={window} className={hours === window ? "active" : ""} onClick={() => setHours(window)} role="tab" aria-selected={hours === window}>{window}h</button>)}</div></div>{error ? <div className="notice">{error}</div> : summary ? <><p className="summary-headline">{summary.aiSummary ?? summary.headline}</p><div className="summary-meta">{summary.aiSummaryStatus === "generated" ? "AI-generated brief · " : "Structured fallback · "}{summary.callCount} calls · {summary.activeThreadCount} active threads · updated {stamp(summary.generatedAt)}</div><div className="summary-sites">{grouped.length ? grouped.map(([site, threads]) => <details className="summary-site" key={site} open><summary><strong>{site}</strong><span>{threads.reduce((total, thread) => total + thread.callCount, 0)} calls</span></summary><div className="summary-channel-list">{threads.map((thread) => <article className="summary-channel" key={thread.key}><div><strong>{thread.talkgroupLabel}</strong><span>{thread.category} · severity {thread.severity}/5 · {thread.callCount} calls</span></div><time>{stamp(thread.firstSeen)}–{stamp(thread.lastSeen)}</time>{thread.locations.length > 0 ? <em>⌖ {thread.locations.map((location) => location.label).join(" · ")}</em> : thread.locationHints.length > 0 ? <em className="location-hint">Hint: {thread.locationHints.join(" · ")}</em> : <em className="location-muted">⌖ no confirmed location</em>}{thread.excerpts.length > 0 && <p>{thread.excerpts[0]}</p>}</article>)}</div></details>) : <div className="empty-state">No calls in this window.</div>}</div></> : <div className="empty-state">Loading activity summary…</div>}</section>;
}
