import { useEffect, useState } from "react";
import { getSystems, saveSystem, type SystemProfile } from "./api";

type Site = NonNullable<SystemProfile["sites"]>[number];

export function SitesEditor() {
  const [profiles, setProfiles] = useState<SystemProfile[]>([]);
  const [selected, setSelected] = useState<SystemProfile>();
  const [status, setStatus] = useState("");
  useEffect(() => { getSystems().then((items) => { setProfiles(items); setSelected(items.find((item) => item.protocol.startsWith("p25")) ?? items[0]); }).catch(() => setStatus("Systems unavailable")); }, []);
  const updateSites = (sites: Site[]) => setSelected((current) => current ? { ...current, sites } : current);
  const add = () => updateSites([...(selected?.sites ?? []), { id: crypto.randomUUID(), name: "New site", controlChannelsHz: [], voiceChannelsHz: [], latitude: undefined, longitude: undefined }]);
  const save = async () => { if (!selected) return; try { const saved = await saveSystem(selected); setSelected(saved); setProfiles((items) => items.map((item) => item.id === saved.id ? saved : item)); setStatus("Sites saved; decoder configuration regenerated"); } catch (error) { setStatus(error instanceof Error ? error.message : "Site save failed"); } };
  if (!profiles.length) return null;
  return <section className="page-card sites-editor"><div className="panel-title"><div><small>SYSTEM SITES</small><h2>Sites and channel plans</h2></div><select value={selected?.id ?? ""} onChange={(event) => setSelected(profiles.find((item) => item.id === event.target.value))}>{profiles.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div>{(selected?.sites ?? []).map((site, index) => <div className="site-row" key={site.id}><input aria-label="Site name" value={site.name} onChange={(event) => updateSites((selected?.sites ?? []).map((item, i) => i === index ? { ...item, name: event.target.value } : item))} /><input aria-label="Control channels" placeholder="Control channels Hz, comma separated" value={site.controlChannelsHz.join(", ")} onChange={(event) => updateSites((selected?.sites ?? []).map((item, i) => i === index ? { ...item, controlChannelsHz: event.target.value.split(",").map(Number).filter((value) => value > 0) } : item))} /><input aria-label="Voice channels" placeholder="Voice channels Hz, comma separated" value={site.voiceChannelsHz.join(", ")} onChange={(event) => updateSites((selected?.sites ?? []).map((item, i) => i === index ? { ...item, voiceChannelsHz: event.target.value.split(",").map(Number).filter((value) => value > 0) } : item))} /><input aria-label="Latitude" placeholder="Latitude" value={site.latitude ?? ""} onChange={(event) => updateSites((selected?.sites ?? []).map((item, i) => i === index ? { ...item, latitude: Number(event.target.value) || undefined } : item))} /><input aria-label="Longitude" placeholder="Longitude" value={site.longitude ?? ""} onChange={(event) => updateSites((selected?.sites ?? []).map((item, i) => i === index ? { ...item, longitude: Number(event.target.value) || undefined } : item))} /><button className="quiet" onClick={() => updateSites((selected?.sites ?? []).filter((_, i) => i !== index))}>REMOVE</button></div>)}<div className="config-actions"><button onClick={add}>ADD SITE</button><button className="primary" onClick={() => void save()}>SAVE SITES</button><span>{status || "Sites persist with the selected system."}</span></div></section>;
}
